export const other = {
    Recipe: {
        difficulty: 'Difficulty:',
        categories: 'Categories:',
        ingredients: 'Ingredients:',
        steps: 'Steps:',
        time: 'Cooking time:',
        video: 'Video',
        cookingTime:
            'This dish will take about <b>~{{count}} minutes to prepare.</b>',
        tips: 'Tips:',
        warnings: 'Warnings:',
        generated: 'Generated by our chatbot',
        user: 'Created manually'
    },
    Stepper: {
        back: 'Back',
        skip: 'Skip',
        next: 'Next',
        submit: 'Finish',
        backToFinalStep: 'Back to Final Step',
        completeStep: 'Complete Step',
        checkStep: 'Check Step',
        incompleteStep: 'Incomplete Step',
        completed: 'Completed',
        step: 'Step',
        Steps: {
            Recipe: {
                '1': {
                    title: 'Name Your Recipe and Set the Basics',
                    description:
                        'Step 1: Give your recipe a name and set the basic information, such as the number of servings and cooking time.'
                },
                '2': {
                    title: 'Describe Your Recipe',
                    description:
                        'Step 2: Write a brief description of your recipe, including its origin, history, or any other interesting facts.'
                },
                '3': {
                    title: 'Upload a Photo',
                    description:
                        'Step 3: Add a photo of your dish to make it more appealing to other users.'
                },
                '4': {
                    title: 'List the Ingredients',
                    description:
                        'Step 4: Add all the ingredients needed to prepare your dish.'
                },
                '5': {
                    title: 'List the Steps',
                    description:
                        'Step 5: Add all the steps needed to prepare your dish.'
                },
                '6': {
                    title: 'Add Tips',
                    description:
                        'Step 6: Add any additional tips or tricks that might help others prepare your dish.'
                },
                '7': {
                    title: 'Add Warnings',
                    description:
                        'Step 7: Add any warnings or precautions that others should be aware of when preparing your dish.'
                },
                '8': {
                    title: 'Add a Video-link',
                    description:
                        'Step 8: Add a video link(YouTube) to your recipe to show others how to prepare it.'
                },
                '9': {
                    title: 'Review and Publish',
                    description: 'Step 9: Review your recipe and publish.'
                }
            },
            MealPlan: {}
        }
    },
    Categories: {
        dishType: 'Dish Types',
        worldCuisine: 'World Cuisine',
        dietaryPreference: 'Dietary Preferences',
        cookingFeatures: 'Cooking Features',
        spiciness: 'Spiciness',
        DishType: {
            breakfast: 'Breakfasts',
            soups: 'Soups',
            salads: 'Salads',
            main_dishes: 'Main Dishes',
            side_dishes: 'Side Dishes',
            desserts: 'Desserts',
            baking: 'Baking',
            drinks: 'Drinks',
            snacks: 'Snacks',
            sauces: 'Sauces and Dips'
        },
        WorldCuisine: {
            italian: 'Italian Cuisine',
            asian: 'Asian Cuisine',
            french: 'French Cuisine',
            american: 'American Cuisine',
            ukrainian: 'Ukrainian Cuisine',
            russian: 'Russian Cuisine',
            mediterranean: 'Mediterranean Cuisine',
            eastern: 'Eastern Cuisine',
            latin: 'Latin American Cuisine'
        },
        DietaryPreference: {
            vegetarian: 'Vegetarian',
            vegan: 'Vegan',
            gluten_free: 'Gluten-Free',
            sugar_free: 'Sugar-Free',
            for_allergy_sufferers: 'For Allergy Sufferers',
            lent: 'Lenten'
        },
        CookingFeatures: {
            quick: 'Quick (under 15 minutes)',
            medium: 'Medium (15-60 minutes)',
            long: 'Long (over 60 minutes)',
            budget: 'Budget-Friendly',
            beginner_friendly: 'Beginner-Friendly',
            kids_friendly: 'Kids-Friendly',
            party: 'Party'
        },
        Spiciness: {
            spicy: 'Spicy',
            medium_spicy: 'Medium',
            not_spicy: 'Not Spicy'
        }
    },

    Pricing: {
        title: 'Our Pricing Plans',
        yourPlan: 'Your Current Plan',
        free: {
            title: 'Free',
            price: 'Free',
            feature1: 'Access to 10 recipes',
            feature2: 'Basic community features',
            feature3: 'Limited support',
            button: 'Get Free'
        },
        basic: {
            title: 'Basic',
            price: '$5/month',
            feature1: 'Access to 50 recipes',
            feature2: 'Basic meal plans',
            feature3: 'Community support',
            button: 'Get Basic'
        },
        standard: {
            title: 'Standard',
            price: '$10/month',
            feature1: 'Access to 200 recipes',
            feature2: 'Standard meal plans',
            feature3: 'Priority support',
            button: 'Get Standard'
        },
        premium: {
            title: 'Premium',
            price: '$20/month',
            feature1: 'Unlimited recipes',
            feature2: 'Custom meal plans',
            feature3: '1-on-1 consultation',
            button: 'Get Premium'
        }
    },
    Rules: {
        description:
            'Please carefully read the TastyTalks community guidelines before posting content (recipes and meal plans) or using information provided by other users or AI:',
        rule1: 'Respect other members of the community. Offensive or discriminatory language is prohibited.',
        rule2: 'Do not publish personal or confidential information about yourself or others.',
        rule3: 'Ensure that recipes and meal plans you publish do not violate copyright laws.',
        rule4: 'Do not publish misleading or harmful dietary advice. Always consult professionals for medical and nutritional guidance.',
        rule5: 'Report inappropriate or harmful content to the administrators.',
        rule6: 'The platform is not responsible for the accuracy of information published by users. Use recipes and dietary advice at your own discretion.',
        rule7: 'The platform does not guarantee that dietary or health advice is suitable for your needs. Always consult a certified specialist before making changes to your diet.',
        rule8: 'The platform cannot be used for illegal activities such as spam, fraud, or malicious software.',
        rule9: 'Mass promotion and advertising are prohibited without prior approval from the administration.',
        rule10: 'Users are responsible for the legality and accuracy of the content they publish.',
        rule11: 'The administration reserves the right to delete accounts for rule violations.',
        rule12: 'The platform may only be used by individuals aged 13 and older. Users under 18 must obtain parental or guardian consent.',
        rule13: 'Users must comply with the laws of their country while using the platform.',
        rule14: 'The administration reserves the right to change the rules and notify users of any changes.',
        rule15: 'Users may add links to external resources, such as YouTube videos and social media profiles, only if they have the right to publish them. The administration reserves the right to remove links that violate platform rules or laws.'
    },
    Privacy: {
        description:
            'Please carefully read our Privacy Policy, which explains how we collect, use, and protect your personal data.',
        rule1: 'We collect personal information, such as name, email, and account details, only with your consent.',
        rule2: 'We use collected data for registration, authentication, notifications, and improving the platform.',
        rule3: 'We use cookies to analyze user behavior and personalize content.',
        rule4: 'Your data is stored securely and is not shared with third parties without your consent.',
        rule5: 'You can request access, deletion, or modification of your data at any time.',
        rule6: 'Data is retained no longer than necessary to fulfill the purposes for which it was collected.',
        rule7: 'The platform is intended for users aged 13 and older. Users under 18 require parental or guardian consent.',
        rule8: 'We reserve the right to modify the Privacy Policy and notify users of any changes.',
        rule9: 'When adding links to external resources (e.g., YouTube videos or social media profiles), the administration does not collect or process data contained in these links. Users are responsible for their accuracy and legality.'
    },
    General: {
        ok: 'OK',
        loading: 'Loading...',
        error: 'Error:',
        close: 'Close',
        cancel: 'Cancel',
        somethingWentWrong: 'Something went wrong, please try again later',
        notAvailable: 'Not available',
        yourQueryTitle: 'Your Query',
        invalidYouTubeUrl: 'Invalid YouTube URL',
        easy: 'Easy',
        medium: 'Medium',
        hard: 'Hard',
        search: 'Search...',
        removePhoto: 'Remove Photo',
        profilePhoto: 'Profile Photo',
        noImage: 'No Image',
        settings: 'Settings',
        confirm: 'Confirm',
        selectAll: 'Select All',
        apply: 'Apply',
        noResultsFound: 'No results found',
        requiredField: 'This field is required',
        back: 'Back',
        follow: 'Follow',
        unfollow: 'Unfollow',
        clickHere: 'Click here',
        or: 'Or',
        selected: 'Selected',
        oops: 'Oops!',
        enterPhoneNumber: 'Enter a number',
        send: 'Send'
    }
};
